apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: devx-mood
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: devx-mood-app
spec:
  source:
    git:
      url: https://github.com/sushilks/mood-portal
      ref:
        branch: main
